title: Joel George Alex – Projects Index
description: A curated showcase of robotics, embedded systems, and design engineering projects.

theme: jekyll-theme-dinky
show_downloads: false

google_analytics: UA-XXXXXXXXX-X  # Replace with your actual Google Analytics Tracking ID, or remove this line if not using

github:
  zip_url: https://github.com/JOELGEORGEALEX/INDEX/archive/refs/heads/main.zip
  repository_url: https://github.com/JOELGEORGEALEX/INDEX
  owner_url: https://github.com/JOELGEORGEALEX
